baseURL = "https://soundportfolio2026.netlify.app/"
languageCode = "en-us"
title = "Mike Ballard"
theme = "congo"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true
[params]
  substackFeed = "https://pushingtheenvelopegenerator.substack.com/feed"

  header.layout = "basic"


  