baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "congo"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.assets]
  disableFingerprinting = false
  disablePipeline = false
  css = ["scss/main.scss"]
